name: link-check
on:
  page_build:
  workflow_dispatch:

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check published links
        uses: JustinBeckwith/linkinator-action@v2
        with:
          paths: https://hemann.pl/course-site-template
          config: linkinator.config.json
          timeout: 15000
